// 서울 지하철 역 목록 및 호선 정보
const LINE_COLORS = {
    '1': '#0052A4',
    '2': '#00A84D',
    '3': '#EF7C1C',
    '4': '#00A5DE',
    '5': '#996CAC',
    '6': '#CD7C2F',
    '7': '#747F00',
    '8': '#E6186C',
    '9': '#BDB092',
    '경의중앙': '#77C4A3',
    '공항철도': '#0090D2',
    '신분당': '#D4003B',
    '수인분당': '#FACC00',
    '경춘': '#0D8140',
    '우이신설': '#B7C450',
    '김포골드': '#AD8605',
    '에버라인': '#56AD2D',
    '의정부': '#FD8100',
    '서해': '#8FC31F',
    'GTX-A': '#9A6292',
};

const LINE_NAMES = {
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    '경의중앙': '경의',
    '공항철도': '공항',
    '신분당': '신분당',
    '수인분당': '수분',
    '경춘': '경춘',
    '우이신설': '우이',
    '김포골드': '김포',
    '에버라인': '에버',
    '의정부': '의정',
    '서해': '서해',
    'GTX-A': 'GTX',
};

// 주요 역 목록 (검색용)
const STATIONS = [
    // 1호선
    { name: '서울역', line: '1' },
    { name: '시청', line: '1' },
    { name: '종각', line: '1' },
    { name: '종로3가', line: '1' },
    { name: '종로5가', line: '1' },
    { name: '동대문', line: '1' },
    { name: '신설동', line: '1' },
    { name: '제기동', line: '1' },
    { name: '청량리', line: '1' },
    { name: '회기', line: '1' },
    { name: '외대앞', line: '1' },
    { name: '신이문', line: '1' },
    { name: '석계', line: '1' },
    { name: '광운대', line: '1' },
    { name: '월계', line: '1' },
    { name: '녹천', line: '1' },
    { name: '창동', line: '1' },
    { name: '방학', line: '1' },
    { name: '도봉', line: '1' },
    { name: '도봉산', line: '1' },
    { name: '망월사', line: '1' },
    { name: '회룡', line: '1' },
    { name: '의정부', line: '1' },
    { name: '남영', line: '1' },
    { name: '용산', line: '1' },
    { name: '노량진', line: '1' },
    { name: '대방', line: '1' },
    { name: '신길', line: '1' },
    { name: '영등포', line: '1' },
    { name: '신도림', line: '1' },
    { name: '구로', line: '1' },
    { name: '구일', line: '1' },
    { name: '개봉', line: '1' },
    { name: '오류동', line: '1' },
    { name: '온수', line: '1' },
    { name: '역곡', line: '1' },
    { name: '소사', line: '1' },
    { name: '부천', line: '1' },
    { name: '중동', line: '1' },
    { name: '송내', line: '1' },
    { name: '부개', line: '1' },
    { name: '부평', line: '1' },
    { name: '백운', line: '1' },
    { name: '동암', line: '1' },
    { name: '간석', line: '1' },
    { name: '주안', line: '1' },
    { name: '도화', line: '1' },
    { name: '제물포', line: '1' },
    { name: '동인천', line: '1' },
    { name: '인천', line: '1' },
    { name: '가산디지털단지', line: '1' },
    { name: '독산', line: '1' },
    { name: '금천구청', line: '1' },

    // 2호선
    { name: '시청', line: '2' },
    { name: '을지로입구', line: '2' },
    { name: '을지로3가', line: '2' },
    { name: '을지로4가', line: '2' },
    { name: '동대문역사문화공원', line: '2' },
    { name: '신당', line: '2' },
    { name: '상왕십리', line: '2' },
    { name: '왕십리', line: '2' },
    { name: '한양대', line: '2' },
    { name: '뚝섬', line: '2' },
    { name: '성수', line: '2' },
    { name: '건대입구', line: '2' },
    { name: '구의', line: '2' },
    { name: '강변', line: '2' },
    { name: '잠실나루', line: '2' },
    { name: '잠실', line: '2' },
    { name: '잠실새내', line: '2' },
    { name: '종합운동장', line: '2' },
    { name: '삼성', line: '2' },
    { name: '선릉', line: '2' },
    { name: '역삼', line: '2' },
    { name: '강남', line: '2' },
    { name: '교대', line: '2' },
    { name: '서초', line: '2' },
    { name: '방배', line: '2' },
    { name: '사당', line: '2' },
    { name: '낙성대', line: '2' },
    { name: '서울대입구', line: '2' },
    { name: '봉천', line: '2' },
    { name: '신림', line: '2' },
    { name: '신대방', line: '2' },
    { name: '구로디지털단지', line: '2' },
    { name: '대림', line: '2' },
    { name: '신도림', line: '2' },
    { name: '문래', line: '2' },
    { name: '영등포구청', line: '2' },
    { name: '당산', line: '2' },
    { name: '합정', line: '2' },
    { name: '홍대입구', line: '2' },
    { name: '신촌', line: '2' },
    { name: '이대', line: '2' },
    { name: '아현', line: '2' },
    { name: '충정로', line: '2' },
    { name: '용답', line: '2' },
    { name: '신답', line: '2' },
    { name: '용두', line: '2' },
    { name: '신설동', line: '2' },
    { name: '도림천', line: '2' },
    { name: '양천구청', line: '2' },
    { name: '신정네거리', line: '2' },
    { name: '까치산', line: '2' },

    // 3호선
    { name: '대화', line: '3' },
    { name: '주엽', line: '3' },
    { name: '정발산', line: '3' },
    { name: '마두', line: '3' },
    { name: '백석', line: '3' },
    { name: '대곡', line: '3' },
    { name: '화정', line: '3' },
    { name: '원당', line: '3' },
    { name: '원흥', line: '3' },
    { name: '삼송', line: '3' },
    { name: '지축', line: '3' },
    { name: '구파발', line: '3' },
    { name: '연신내', line: '3' },
    { name: '불광', line: '3' },
    { name: '녹번', line: '3' },
    { name: '홍제', line: '3' },
    { name: '무악재', line: '3' },
    { name: '독립문', line: '3' },
    { name: '경복궁', line: '3' },
    { name: '안국', line: '3' },
    { name: '종로3가', line: '3' },
    { name: '을지로3가', line: '3' },
    { name: '충무로', line: '3' },
    { name: '동대입구', line: '3' },
    { name: '약수', line: '3' },
    { name: '금호', line: '3' },
    { name: '옥수', line: '3' },
    { name: '압구정', line: '3' },
    { name: '신사', line: '3' },
    { name: '잠원', line: '3' },
    { name: '고속터미널', line: '3' },
    { name: '교대', line: '3' },
    { name: '남부터미널', line: '3' },
    { name: '양재', line: '3' },
    { name: '매봉', line: '3' },
    { name: '도곡', line: '3' },
    { name: '대치', line: '3' },
    { name: '학여울', line: '3' },
    { name: '대청', line: '3' },
    { name: '일원', line: '3' },
    { name: '수서', line: '3' },
    { name: '가락시장', line: '3' },
    { name: '경찰병원', line: '3' },
    { name: '오금', line: '3' },

    // 4호선
    { name: '당고개', line: '4' },
    { name: '상계', line: '4' },
    { name: '노원', line: '4' },
    { name: '창동', line: '4' },
    { name: '쌍문', line: '4' },
    { name: '수유', line: '4' },
    { name: '미아', line: '4' },
    { name: '미아사거리', line: '4' },
    { name: '길음', line: '4' },
    { name: '성신여대입구', line: '4' },
    { name: '한성대입구', line: '4' },
    { name: '혜화', line: '4' },
    { name: '동대문', line: '4' },
    { name: '동대문역사문화공원', line: '4' },
    { name: '충무로', line: '4' },
    { name: '명동', line: '4' },
    { name: '회현', line: '4' },
    { name: '서울역', line: '4' },
    { name: '숙대입구', line: '4' },
    { name: '삼각지', line: '4' },
    { name: '신용산', line: '4' },
    { name: '이촌', line: '4' },
    { name: '동작', line: '4' },
    { name: '총신대입구', line: '4' },
    { name: '사당', line: '4' },
    { name: '남태령', line: '4' },
    { name: '선바위', line: '4' },
    { name: '경마공원', line: '4' },
    { name: '대공원', line: '4' },
    { name: '과천', line: '4' },
    { name: '정부과천청사', line: '4' },
    { name: '인덕원', line: '4' },
    { name: '평촌', line: '4' },
    { name: '범계', line: '4' },
    { name: '금정', line: '4' },
    { name: '산본', line: '4' },
    { name: '수리산', line: '4' },
    { name: '대야미', line: '4' },
    { name: '반월', line: '4' },
    { name: '상록수', line: '4' },
    { name: '한대앞', line: '4' },
    { name: '중앙', line: '4' },
    { name: '고잔', line: '4' },
    { name: '초지', line: '4' },
    { name: '안산', line: '4' },
    { name: '신길온천', line: '4' },
    { name: '정왕', line: '4' },
    { name: '오이도', line: '4' },

    // 5호선
    { name: '방화', line: '5' },
    { name: '개화산', line: '5' },
    { name: '김포공항', line: '5' },
    { name: '송정', line: '5' },
    { name: '마곡', line: '5' },
    { name: '발산', line: '5' },
    { name: '우장산', line: '5' },
    { name: '화곡', line: '5' },
    { name: '까치산', line: '5' },
    { name: '신정', line: '5' },
    { name: '목동', line: '5' },
    { name: '오목교', line: '5' },
    { name: '양평', line: '5' },
    { name: '영등포구청', line: '5' },
    { name: '영등포시장', line: '5' },
    { name: '신길', line: '5' },
    { name: '여의도', line: '5' },
    { name: '여의나루', line: '5' },
    { name: '마포', line: '5' },
    { name: '공덕', line: '5' },
    { name: '애오개', line: '5' },
    { name: '충정로', line: '5' },
    { name: '서대문', line: '5' },
    { name: '광화문', line: '5' },
    { name: '종로3가', line: '5' },
    { name: '을지로4가', line: '5' },
    { name: '동대문역사문화공원', line: '5' },
    { name: '청구', line: '5' },
    { name: '신금호', line: '5' },
    { name: '행당', line: '5' },
    { name: '왕십리', line: '5' },
    { name: '마장', line: '5' },
    { name: '답십리', line: '5' },
    { name: '장한평', line: '5' },
    { name: '군자', line: '5' },
    { name: '아차산', line: '5' },
    { name: '광나루', line: '5' },
    { name: '천호', line: '5' },
    { name: '강동', line: '5' },
    { name: '길동', line: '5' },
    { name: '굽은다리', line: '5' },
    { name: '명일', line: '5' },
    { name: '고덕', line: '5' },
    { name: '상일동', line: '5' },
    { name: '강일', line: '5' },
    { name: '미사', line: '5' },
    { name: '하남풍산', line: '5' },
    { name: '하남시청', line: '5' },
    { name: '하남검단산', line: '5' },
    { name: '둔촌동', line: '5' },
    { name: '올림픽공원', line: '5' },
    { name: '방이', line: '5' },
    { name: '오금', line: '5' },
    { name: '개롱', line: '5' },
    { name: '거여', line: '5' },
    { name: '마천', line: '5' },

    // 6호선
    { name: '응암', line: '6' },
    { name: '역촌', line: '6' },
    { name: '불광', line: '6' },
    { name: '독바위', line: '6' },
    { name: '연신내', line: '6' },
    { name: '구산', line: '6' },
    { name: '새절', line: '6' },
    { name: '증산', line: '6' },
    { name: '디지털미디어시티', line: '6' },
    { name: '월드컵경기장', line: '6' },
    { name: '마포구청', line: '6' },
    { name: '망원', line: '6' },
    { name: '합정', line: '6' },
    { name: '상수', line: '6' },
    { name: '광흥창', line: '6' },
    { name: '대흥', line: '6' },
    { name: '공덕', line: '6' },
    { name: '효창공원앞', line: '6' },
    { name: '삼각지', line: '6' },
    { name: '녹사평', line: '6' },
    { name: '이태원', line: '6' },
    { name: '한강진', line: '6' },
    { name: '버티고개', line: '6' },
    { name: '약수', line: '6' },
    { name: '청구', line: '6' },
    { name: '신당', line: '6' },
    { name: '동묘앞', line: '6' },
    { name: '창신', line: '6' },
    { name: '보문', line: '6' },
    { name: '안암', line: '6' },
    { name: '고려대', line: '6' },
    { name: '월곡', line: '6' },
    { name: '상월곡', line: '6' },
    { name: '돌곶이', line: '6' },
    { name: '석계', line: '6' },
    { name: '태릉입구', line: '6' },
    { name: '화랑대', line: '6' },
    { name: '봉화산', line: '6' },
    { name: '신내', line: '6' },

    // 7호선
    { name: '장암', line: '7' },
    { name: '도봉산', line: '7' },
    { name: '수락산', line: '7' },
    { name: '마들', line: '7' },
    { name: '노원', line: '7' },
    { name: '중계', line: '7' },
    { name: '하계', line: '7' },
    { name: '공릉', line: '7' },
    { name: '태릉입구', line: '7' },
    { name: '먹골', line: '7' },
    { name: '중화', line: '7' },
    { name: '상봉', line: '7' },
    { name: '면목', line: '7' },
    { name: '사가정', line: '7' },
    { name: '용마산', line: '7' },
    { name: '중곡', line: '7' },
    { name: '군자', line: '7' },
    { name: '어린이대공원', line: '7' },
    { name: '건대입구', line: '7' },
    { name: '뚝섬유원지', line: '7' },
    { name: '청담', line: '7' },
    { name: '강남구청', line: '7' },
    { name: '학동', line: '7' },
    { name: '논현', line: '7' },
    { name: '반포', line: '7' },
    { name: '고속터미널', line: '7' },
    { name: '내방', line: '7' },
    { name: '이수', line: '7' },
    { name: '남성', line: '7' },
    { name: '숭실대입구', line: '7' },
    { name: '상도', line: '7' },
    { name: '장승배기', line: '7' },
    { name: '신대방삼거리', line: '7' },
    { name: '보라매', line: '7' },
    { name: '신풍', line: '7' },
    { name: '대림', line: '7' },
    { name: '남구로', line: '7' },
    { name: '가산디지털단지', line: '7' },
    { name: '철산', line: '7' },
    { name: '광명사거리', line: '7' },
    { name: '천왕', line: '7' },
    { name: '온수', line: '7' },
    { name: '까치울', line: '7' },
    { name: '부천종합운동장', line: '7' },
    { name: '춘의', line: '7' },
    { name: '신중동', line: '7' },
    { name: '부천시청', line: '7' },
    { name: '상동', line: '7' },
    { name: '삼산체육관', line: '7' },
    { name: '굴포천', line: '7' },
    { name: '부평구청', line: '7' },
    { name: '산곡', line: '7' },
    { name: '석남', line: '7' },

    // 8호선
    { name: '암사', line: '8' },
    { name: '천호', line: '8' },
    { name: '강동구청', line: '8' },
    { name: '몽촌토성', line: '8' },
    { name: '잠실', line: '8' },
    { name: '석촌', line: '8' },
    { name: '송파', line: '8' },
    { name: '가락시장', line: '8' },
    { name: '문정', line: '8' },
    { name: '장지', line: '8' },
    { name: '복정', line: '8' },
    { name: '산성', line: '8' },
    { name: '남한산성입구', line: '8' },
    { name: '단대오거리', line: '8' },
    { name: '신흥', line: '8' },
    { name: '수진', line: '8' },
    { name: '모란', line: '8' },

    // 9호선
    { name: '개화', line: '9' },
    { name: '김포공항', line: '9' },
    { name: '공항시장', line: '9' },
    { name: '신방화', line: '9' },
    { name: '마곡나루', line: '9' },
    { name: '양천향교', line: '9' },
    { name: '가양', line: '9' },
    { name: '증미', line: '9' },
    { name: '등촌', line: '9' },
    { name: '염창', line: '9' },
    { name: '신목동', line: '9' },
    { name: '선유도', line: '9' },
    { name: '당산', line: '9' },
    { name: '국회의사당', line: '9' },
    { name: '여의도', line: '9' },
    { name: '샛강', line: '9' },
    { name: '노량진', line: '9' },
    { name: '노들', line: '9' },
    { name: '흑석', line: '9' },
    { name: '동작', line: '9' },
    { name: '구반포', line: '9' },
    { name: '신반포', line: '9' },
    { name: '고속터미널', line: '9' },
    { name: '사평', line: '9' },
    { name: '신논현', line: '9' },
    { name: '언주', line: '9' },
    { name: '선정릉', line: '9' },
    { name: '삼성중앙', line: '9' },
    { name: '봉은사', line: '9' },
    { name: '종합운동장', line: '9' },
    { name: '삼전', line: '9' },
    { name: '석촌고분', line: '9' },
    { name: '석촌', line: '9' },
    { name: '송파나루', line: '9' },
    { name: '한성백제', line: '9' },
    { name: '올림픽공원', line: '9' },
    { name: '둔촌오륜', line: '9' },
    { name: '중앙보훈병원', line: '9' },

    // 신분당선
    { name: '신사', line: '신분당' },
    { name: '논현', line: '신분당' },
    { name: '신논현', line: '신분당' },
    { name: '강남', line: '신분당' },
    { name: '양재', line: '신분당' },
    { name: '양재시민의숲', line: '신분당' },
    { name: '청계산입구', line: '신분당' },
    { name: '판교', line: '신분당' },
    { name: '정자', line: '신분당' },
    { name: '미금', line: '신분당' },
    { name: '동천', line: '신분당' },
    { name: '수지구청', line: '신분당' },
    { name: '성복', line: '신분당' },
    { name: '상현', line: '신분당' },
    { name: '광교중앙', line: '신분당' },
    { name: '광교', line: '신분당' },

    // GTX-A
    { name: '수서', line: 'GTX-A' },
    { name: '성남', line: 'GTX-A' },
    { name: '구성', line: 'GTX-A' },
    { name: '동탄', line: 'GTX-A' },
    { name: '서울역', line: 'GTX-A' },
    { name: '연신내', line: 'GTX-A' },
    { name: '대곡', line: 'GTX-A' },
    { name: '킨텍스', line: 'GTX-A' },
    { name: '운정중앙', line: 'GTX-A' },

    // 경의중앙선
    { name: '문산', line: '경의중앙' },
    { name: '파주', line: '경의중앙' },
    { name: '월롱', line: '경의중앙' },
    { name: '금촌', line: '경의중앙' },
    { name: '금릉', line: '경의중앙' },
    { name: '운정', line: '경의중앙' },
    { name: '야당', line: '경의중앙' },
    { name: '탄현', line: '경의중앙' },
    { name: '일산', line: '경의중앙' },
    { name: '풍산', line: '경의중앙' },
    { name: '백마', line: '경의중앙' },
    { name: '곡산', line: '경의중앙' },
    { name: '대곡', line: '경의중앙' },
    { name: '능곡', line: '경의중앙' },
    { name: '행신', line: '경의중앙' },
    { name: '강매', line: '경의중앙' },
    { name: '화전', line: '경의중앙' },
    { name: '수색', line: '경의중앙' },
    { name: '디지털미디어시티', line: '경의중앙' },
    { name: '가좌', line: '경의중앙' },
    { name: '홍대입구', line: '경의중앙' },
    { name: '서강대', line: '경의중앙' },
    { name: '공덕', line: '경의중앙' },
    { name: '효창공원앞', line: '경의중앙' },
    { name: '용산', line: '경의중앙' },
    { name: '이촌', line: '경의중앙' },
    { name: '서빙고', line: '경의중앙' },
    { name: '한남', line: '경의중앙' },
    { name: '옥수', line: '경의중앙' },
    { name: '응봉', line: '경의중앙' },
    { name: '왕십리', line: '경의중앙' },
    { name: '청량리', line: '경의중앙' },
    { name: '회기', line: '경의중앙' },
    { name: '중랑', line: '경의중앙' },
    { name: '상봉', line: '경의중앙' },
    { name: '망우', line: '경의중앙' },
    { name: '양원', line: '경의중앙' },
    { name: '구리', line: '경의중앙' },
    { name: '도농', line: '경의중앙' },
    { name: '양정', line: '경의중앙' },
    { name: '덕소', line: '경의중앙' },
    { name: '도심', line: '경의중앙' },
    { name: '팔당', line: '경의중앙' },
    { name: '운길산', line: '경의중앙' },
    { name: '양수', line: '경의중앙' },
    { name: '신원', line: '경의중앙' },
    { name: '국수', line: '경의중앙' },
    { name: '아신', line: '경의중앙' },
    { name: '오빈', line: '경의중앙' },
    { name: '양평', line: '경의중앙' },
    { name: '원덕', line: '경의중앙' },
    { name: '용문', line: '경의중앙' },
    { name: '지평', line: '경의중앙' },

    // 공항철도
    { name: '인천공항1터미널', line: '공항철도' },
    { name: '인천공항2터미널', line: '공항철도' },
    { name: '공항화물청사', line: '공항철도' },
    { name: '운서', line: '공항철도' },
    { name: '영종', line: '공항철도' },
    { name: '청라국제도시', line: '공항철도' },
    { name: '검암', line: '공항철도' },
    { name: '계양', line: '공항철도' },
    { name: '김포공항', line: '공항철도' },
    { name: '디지털미디어시티', line: '공항철도' },
    { name: '홍대입구', line: '공항철도' },
    { name: '공덕', line: '공항철도' },
    { name: '서울역', line: '공항철도' },

    // 수인분당선
    { name: '청량리', line: '수인분당' },
    { name: '왕십리', line: '수인분당' },
    { name: '서울숲', line: '수인분당' },
    { name: '압구정로데오', line: '수인분당' },
    { name: '강남구청', line: '수인분당' },
    { name: '선정릉', line: '수인분당' },
    { name: '선릉', line: '수인분당' },
    { name: '한티', line: '수인분당' },
    { name: '도곡', line: '수인분당' },
    { name: '구룡', line: '수인분당' },
    { name: '개포동', line: '수인분당' },
    { name: '대모산입구', line: '수인분당' },
    { name: '수서', line: '수인분당' },
    { name: '복정', line: '수인분당' },
    { name: '가천대', line: '수인분당' },
    { name: '태평', line: '수인분당' },
    { name: '모란', line: '수인분당' },
    { name: '야탑', line: '수인분당' },
    { name: '이매', line: '수인분당' },
    { name: '서현', line: '수인분당' },
    { name: '수내', line: '수인분당' },
    { name: '정자', line: '수인분당' },
    { name: '미금', line: '수인분당' },
    { name: '오리', line: '수인분당' },
    { name: '죽전', line: '수인분당' },
    { name: '보정', line: '수인분당' },
    { name: '구성', line: '수인분당' },
    { name: '신갈', line: '수인분당' },
    { name: '기흥', line: '수인분당' },
    { name: '상갈', line: '수인분당' },
    { name: '청명', line: '수인분당' },
    { name: '영통', line: '수인분당' },
    { name: '망포', line: '수인분당' },
    { name: '매탄권선', line: '수인분당' },
    { name: '수원시청', line: '수인분당' },
    { name: '매교', line: '수인분당' },
    { name: '수원', line: '수인분당' },
    { name: '고색', line: '수인분당' },
    { name: '오목천', line: '수인분당' },
    { name: '어천', line: '수인분당' },
    { name: '야목', line: '수인분당' },
    { name: '사리', line: '수인분당' },
    { name: '한대앞', line: '수인분당' },
    { name: '중앙', line: '수인분당' },
    { name: '고잔', line: '수인분당' },
    { name: '초지', line: '수인분당' },
    { name: '안산', line: '수인분당' },
    { name: '신길온천', line: '수인분당' },
    { name: '정왕', line: '수인분당' },
    { name: '오이도', line: '수인분당' },
    { name: '달월', line: '수인분당' },
    { name: '월곶', line: '수인분당' },
    { name: '소래포구', line: '수인분당' },
    { name: '인천논현', line: '수인분당' },
    { name: '호구포', line: '수인분당' },
    { name: '남동인더스파크', line: '수인분당' },
    { name: '원인재', line: '수인분당' },
    { name: '연수', line: '수인분당' },
    { name: '송도', line: '수인분당' },
    { name: '인하대', line: '수인분당' },
    { name: '숭의', line: '수인분당' },
    { name: '신포', line: '수인분당' },
    { name: '인천', line: '수인분당' },

    // 경춘선
    { name: '청량리', line: '경춘' },
    { name: '회기', line: '경춘' },
    { name: '중랑', line: '경춘' },
    { name: '상봉', line: '경춘' },
    { name: '망우', line: '경춘' },
    { name: '신내', line: '경춘' },
    { name: '갈매', line: '경춘' },
    { name: '별내', line: '경춘' },
    { name: '퇴계원', line: '경춘' },
    { name: '사릉', line: '경춘' },
    { name: '금곡', line: '경춘' },
    { name: '평내호평', line: '경춘' },
    { name: '천마산', line: '경춘' },
    { name: '마석', line: '경춘' },
    { name: '대성리', line: '경춘' },
    { name: '청평', line: '경춘' },
    { name: '상천', line: '경춘' },
    { name: '가평', line: '경춘' },
    { name: '굴봉산', line: '경춘' },
    { name: '백양리', line: '경춘' },
    { name: '강촌', line: '경춘' },
    { name: '김유정', line: '경춘' },
    { name: '남춘천', line: '경춘' },
    { name: '춘천', line: '경춘' },

    // 우이신설선
    { name: '북한산우이', line: '우이신설' },
    { name: '솔밭공원', line: '우이신설' },
    { name: '4.19민주묘지', line: '우이신설' },
    { name: '가오리', line: '우이신설' },
    { name: '화계', line: '우이신설' },
    { name: '삼양', line: '우이신설' },
    { name: '삼양사거리', line: '우이신설' },
    { name: '솔샘', line: '우이신설' },
    { name: '북한산보국문', line: '우이신설' },
    { name: '정릉', line: '우이신설' },
    { name: '성신여대입구', line: '우이신설' },
    { name: '보문', line: '우이신설' },
    { name: '신설동', line: '우이신설' },
];

// 호선 색상 가져오기
function getLineColor(line) {
    return LINE_COLORS[line] || '#888888';
}

// 호선 약어 가져오기
function getLineName(line) {
    return LINE_NAMES[line] || line;
}

// 초성 추출
const CHOSEONG = ['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];

function getChoseong(str) {
    let result = '';
    for (const char of str) {
        const code = char.charCodeAt(0) - 0xAC00;
        if (code >= 0 && code <= 11171) {
            result += CHOSEONG[Math.floor(code / 588)];
        } else {
            result += char;
        }
    }
    return result;
}

// 초성만으로 이루어진 문자열인지 확인
function isChoseongOnly(str) {
    return /^[ㄱ-ㅎ]+$/.test(str);
}

// 편집 거리 (Levenshtein Distance) - 오타 허용
function getEditDistance(a, b) {
    if (a.length === 0) return b.length;
    if (b.length === 0) return a.length;

    const matrix = [];
    for (let i = 0; i <= b.length; i++) {
        matrix[i] = [i];
    }
    for (let j = 0; j <= a.length; j++) {
        matrix[0][j] = j;
    }

    for (let i = 1; i <= b.length; i++) {
        for (let j = 1; j <= a.length; j++) {
            if (b.charAt(i - 1) === a.charAt(j - 1)) {
                matrix[i][j] = matrix[i - 1][j - 1];
            } else {
                matrix[i][j] = Math.min(
                    matrix[i - 1][j - 1] + 1,
                    matrix[i][j - 1] + 1,
                    matrix[i - 1][j] + 1
                );
            }
        }
    }
    return matrix[b.length][a.length];
}

// 역 검색 (초성검색 + 오타 허용)
function searchStations(query) {
    if (!query || query.length === 0) return [];

    const normalizedQuery = query.toLowerCase().replace(/역$/, '');
    const isChoseong = isChoseongOnly(normalizedQuery);

    // 점수 기반 검색 결과
    const results = STATIONS.map(station => {
        const name = station.name.toLowerCase();
        let score = 0;

        // 1. 정확히 일치
        if (name === normalizedQuery) {
            score = 100;
        }
        // 2. 시작 부분 일치
        else if (name.startsWith(normalizedQuery)) {
            score = 90;
        }
        // 3. 포함
        else if (name.includes(normalizedQuery)) {
            score = 80;
        }
        // 4. 초성 검색
        else if (isChoseong) {
            const choseong = getChoseong(name);
            if (choseong.startsWith(normalizedQuery)) {
                score = 70;
            } else if (choseong.includes(normalizedQuery)) {
                score = 60;
            }
        }
        // 5. 오타 허용 (편집 거리 1~2)
        else if (normalizedQuery.length >= 2) {
            const distance = getEditDistance(name, normalizedQuery);
            if (distance === 1) {
                score = 50;
            } else if (distance === 2 && normalizedQuery.length >= 3) {
                score = 40;
            }
        }

        return { station, score };
    })
    .filter(r => r.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10)
    .map(r => r.station);

    return results;
}
